# Generated by Django 3.0.1 on 2020-02-07 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='svgimg',
            field=models.FileField(upload_to='svgimg', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
