# Generated by Django 3.0.1 on 2020-02-07 15:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200207_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1920, 834], upload_to='homeslider'),
        ),
    ]
