# Generated by Django 3.0.1 on 2020-02-08 18:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_auto_20200207_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
