# Generated by Django 3.0.1 on 2020-02-15 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_auto_20200209_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=250)),
                ('svgimg', models.FileField(upload_to='svgimg2', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
            ],
        ),
    ]
