# Generated by Django 3.0.1 on 2020-02-15 18:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0013_homestatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercontact',
            name='contact_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
