# Generated by Django 3.0.1 on 2020-02-20 18:47

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0016_auto_20200219_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us_fixed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('aboutimg', models.ImageField(upload_to='others')),
                ('whybackground', models.ImageField(upload_to='others')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='team')),
                ('name', models.CharField(max_length=100)),
                ('shortdesc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='why_choose_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='why_choose', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('img', models.ImageField(upload_to='why_choose')),
                ('title', models.CharField(max_length=100)),
                ('shortdesc', models.CharField(max_length=200)),
            ],
        ),
    ]
