# Generated by Django 3.0.1 on 2020-02-25 18:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0017_about_us_fixed_team_why_choose_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us_fixed',
            options={'verbose_name': 'About Us Section'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Our Team'},
        ),
        migrations.AlterModelOptions(
            name='why_choose_us',
            options={'ordering': ['-title'], 'verbose_name': 'Why Choose Us'},
        ),
        migrations.AlterField(
            model_name='about_us_fixed',
            name='brief',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description About'),
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='team', verbose_name='Picture'),
        ),
    ]
