# Generated by Django 3.0.1 on 2020-02-26 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0018_auto_20200226_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
