# Generated by Django 3.0.1 on 2020-03-09 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0022_auto_20200227_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 10, 0, 7, 49, 525888)),
        ),
    ]
