# Generated by Django 3.0.1 on 2020-02-25 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_address_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 25, 19, 15, 8, 843238, tzinfo=utc)),
        ),
    ]
