# Generated by Django 3.0.1 on 2020-02-26 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200226_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 27, 0, 45, 32, 901371)),
        ),
    ]
