# Generated by Django 3.0.1 on 2020-03-09 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200227_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 10, 0, 7, 49, 611888)),
        ),
    ]
