# Generated by Django 3.0.1 on 2020-03-09 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200310_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 10, 0, 17, 4, 663423)),
        ),
    ]
