# Generated by Django 3.0.1 on 2020-02-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besttrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=70)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='offpics')),
            ],
        ),
    ]
