# Generated by Django 3.0.1 on 2020-02-07 15:58

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_auto_20200207_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='img',
            field=stdimage.models.StdImageField(upload_to='homeslider'),
        ),
    ]
